#!/bin/sh
# Set $HOME vars before running i3 - for dmenu

# shellcheck source=/home/piranha/.profile
. "$HOME/.profile"

if [ -f "$HOME/.Xresources" ]; then
  xrdb -merge ~/.Xresources
fi

if [ -f "$HOME/.Xmodmap"  ]; then
  xmodmap ~/.Xmodmap
fi
